name: ocsf-validator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: "./.github/actions/setup"
        with:
          python-version: ${{ matrix.python-version }}
      - name: pytest
        shell: bash
        run: poetry run pytest
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: "./.github/actions/setup"
        with:
          python-version: "3.12"
      - name: black
        shell: bash
        run: poetry run black --check .
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: "./.github/actions/setup"
        with:
          python-version: "3.12"
      - name: isort
        shell: bash
        run: poetry run isort --check .
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: "./.github/actions/setup"
        with:
          python-version: "3.12"
      - name: pyright
        shell: bash
        run: poetry run pyright